### ISSUE TITLE
[Feature request] HugoMods module to integrate Sveltia CMS

### ISSUE THREAD

**Issue by ezzle** [hugomods/base#42]
## Requested Feature
A HugoMods module to support the Feature rich Sveltia CMS, Alternative to Netlify/Decap CMS. Modern, fast, lightweight, Git-based headless CMS ... May be implemented as a global Module for headless Decap and Sveltia CMS

## What is Sveltia

Alternative to Netlify/Decap CMS. Modern, fast, lightweight, Git-based headless CMS. Free & open source. UX-driven development. Made with Svelte.

`
Sveltia CMS is a Git-based lightweight headless CMS under active development as a modern, quick replacement for Netlify CMS and [Decap CMS](https://decapcms.org/). In some simple cases, migration is as easy as a single line of code change, although we’re still working on improving compatibility. The free, open source, UX-focused alternative to Netlify/Decap CMS 
`
## Third party integration

https://github.com/privatemaker/headless-cms
Hugo Module for headless Decap and Sveltia CMS

Best regards,

Tshitshi

**Comment by razonyang** [comment]
Thanks for the idea, we have module for Decap CMS (larger community) already, https://github.com/hugomods/decap-cms, I'm not planing to implement an alternative.

Btw, I'd suggest sharing ideas on [Discussion](https://github.com/orgs/hugomods/discussions) instead of this repo.
